name: "Check for synced branches action"
description: "An action to easily check if 2 branches are up to date"
branding:
  icon: git-branch
  color: red
inputs:
  upstream-url:
    description: "The URL to the upstream repository if the second branch is from another repo"
    required: false
    default: null
  both-upstream:
    description: "A boolean to check if both branches are upstream"
    required: false
    default: false
  first-branch:
    description: "The name of the first branch in the comparison"
    required: true
    default: "master"
  second-branch:
    description: "The name of the second branch to compare"
    required: true
    default: null
outputs:
  ahead:
    description: "The number of changes the first branch is ahead of the second"
    value: ${{ steps.check.outputs.ahead }}
  behind:
    description: "The number of changes the first branch is behind the second"
    value: ${{ steps.check.outputs.behind }}
runs:
  using: "composite"
  steps:
    - id: check 
      shell: bash
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git fetch --all
        if [[ ${{ inputs.upstream-url }} == null ]]; then
          echo "behind=$(git rev-list --count ${{ inputs.first-branch }}..${{ inputs.second-branch }})" >> $GITHUB_OUTPUT
          echo "ahead=$(git rev-list --count ${{ inputs.second-branch }}..${{ inputs.first-branch }})" >> $GITHUB_OUTPUT
        else
          echo -e "\x1b[32mSyncing repo with upstream ${{ inputs.upstream-url }}!\x1b[0m"
          git remote add upstream ${{ inputs.upstream-url }}.git
          git fetch --all
          if [[ true == ${{ inputs.both-upstream }} ]]; then
            echo -e "\x1b[32mSyncing repos with both being upstream\x1b[0m"
            echo "behind=$(git rev-list --count upstream/${{ inputs.first-branch }}..upstream/${{ inputs.second-branch }})" >> $GITHUB_OUTPUT
            echo "ahead=$(git rev-list --count upstream/${{ inputs.second-branch }}..upstream/${{ inputs.first-branch }})" >> $GITHUB_OUTPUT
          else
            echo -e "\x1b[32mSyncing repos with the second one being upstream!\x1b[0m"
            echo "behind=$(git rev-list --count origin/${{ inputs.first-branch }}..upstream/${{ inputs.second-branch }})" >> $GITHUB_OUTPUT
            echo "ahead=$(git rev-list --count upstream/${{ inputs.second-branch }}..origin/${{ inputs.first-branch }})" >> $GITHUB_OUTPUT
          fi
          git remote remove upstream
        fi
